apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: purubaranwal/onilne-exam-voting-worker:latest
        imagePullPolicy: IfNotPresent
        name: worker
